// Admin allowlist — shared by server routes, middleware, and client-side
// page guards. Update this one place when adding/removing an admin.
export const ADMIN_EMAILS = ["ryan@luckimages.com", "leif@luckimages.com"];

// Flip to true when you're ready to send transactional emails to clients
// (booking confirmations, delivery notifications, invoice notifications).
// Portal invites, outreach, and password resets are unaffected.
export const CLIENT_EMAILS_ENABLED = false;

// Marks a cold_calls "sent_text" row as generated by the tracked-link copy
// button (as opposed to manually tagging "Sent Text" while logging a call
// the old way) — there's no dedicated column for this, so it's folded into
// notes like the existing "ACCESS: " convention. Written by
// admin/cold-calls, read back by dashboard/outreach to isolate just the
// tracked-link sends for the "Cold Call Texts" engagement tab.
export const COLD_CALL_TEXT_LINK_NOTE = "Sent via tracked link";

export const GOOGLE_REVIEW_URL = "https://search.google.com/local/writereview?placeid=ChIJHe2jnlT862ifXEoTm94j1A";
