// Admin allowlist — shared by server routes, middleware, and client-side
// page guards. Update this one place when adding/removing an admin.
export const ADMIN_EMAILS = ["ryan@luckimages.com", "leif@luckimages.com"];

// Flip to true when you're ready to send transactional emails to clients
// (booking confirmations, delivery notifications, invoice notifications).
// Portal invites, outreach, and password resets are unaffected.
export const CLIENT_EMAILS_ENABLED = false;

// Marks a cold_calls "sent_text" row as generated by the tracked-link copy
// button (as opposed to manually tagging "Sent Text" while logging a call
// the old way) — there's no dedicated column for this, so it's folded into
// notes like the existing "ACCESS: " convention. Written by
// admin/cold-calls, read back by dashboard/outreach to isolate just the
// tracked-link sends for the "Cold Call Texts" engagement tab.
export const COLD_CALL_TEXT_LINK_NOTE = "Sent via tracked link";

export const GOOGLE_REVIEW_URL = "https://search.google.com/local/writereview?placeid=ChIJHe2jnlT862ifXEoTm94j1A";

// Admin-authored emails (outreach, quick send, cold-call follow-ups,
// reschedule asks) send AS whoever clicked send — so replies land in their
// inbox and Engagement can show who did the outreach. All @luckimages.com,
// covered by the one verified Resend domain.
const ADMIN_SENDERS: Record<string, { name: string; email: string }> = {
  "ryan@luckimages.com": { name: "Ryan Luck", email: "ryan@luckimages.com" },
  "leif@luckimages.com": { name: "Leif Tilton", email: "leif@luckimages.com" },
};

export function adminSender(email?: string | null): { from: string; replyTo: string; shortName: string; fullName: string } {
  const s = ADMIN_SENDERS[(email || "").toLowerCase()] || ADMIN_SENDERS["ryan@luckimages.com"];
  return { from: `${s.name} <${s.email}>`, replyTo: s.email, shortName: s.name.split(" ")[0], fullName: s.name };
}

// Admin-authored emails carry this token where the sender's name belongs.
// The send-email route swaps it for the actual sender (Ryan or Leif) so the
// signature always matches the From address. Keep the literal string in sync
// with the replace in /api/admin/send-email.
export const SENDER_NAME_TOKEN = "{{SENDER_NAME}}";
export const SENDER_EMAIL_TOKEN = "{{SENDER_EMAIL}}";
