import type { SupabaseClient } from "@supabase/supabase-js";
import { normalizePhone } from "@/lib/format";
import { setFollowUp, todayCentral } from "@/lib/followUps";

export type WebLeadSource = "website-form" | "website-quote";

const escapeLike = (s: string) => s.replace(/[\\%_]/g, c => `\\${c}`);

// Turns a website contact-form / quote submission into a CRM contact: matches
// an existing contact by email, then by phone (last 10 digits — contacts store
// "(512) 555-1234", forms send anything), otherwise creates a new lead.
// Never overwrites an existing contact's lead source ("Lead Generated By" and
// lead source drive attribution/commission and change only via approval).
export async function matchOrCreateLeadContact(
  db: SupabaseClient,
  lead: { name: string; email: string | null; phone: string | null; source: WebLeadSource },
): Promise<{ id: string; created: boolean }> {
  type Match = { id: string; stage: string | null; phone?: string | null };
  let match: Match | null = null;

  const email = lead.email?.trim();
  if (email) {
    const { data } = await db.from("contacts").select("id, stage").ilike("email", escapeLike(email)).limit(1);
    match = data?.[0] ?? null;
  }

  const digits = (lead.phone || "").replace(/\D/g, "").slice(-10);
  if (!match && digits.length === 10) {
    const { data } = await db.from("contacts").select("id, stage, phone").not("phone", "is", null);
    match = (data || []).find((c: Match) => (c.phone || "").replace(/\D/g, "").slice(-10) === digits) ?? null;
  }

  if (match) {
    // A dead or deleted lead reaching out again is a live lead again.
    if (match.stage === "dead" || match.stage === "deleted") {
      await db.from("contacts").update({ stage: "new", updated_at: new Date().toISOString() }).eq("id", match.id);
    }
    return { id: match.id, created: false };
  }

  const { data, error } = await db.from("contacts").insert({
    name: lead.name.trim() || email || "Website lead",
    email: email || null,
    phone: normalizePhone(lead.phone),
    type: "lead",
    stage: "new",
    lead_source: lead.source,
  }).select("id").single();
  if (error) throw error;
  return { id: data.id, created: true };
}

// Everything a website lead needs in Nocturne after the inquiry row is saved:
// a contact, and a "call them" follow-up due today. Returns the contact id, or
// null if anything failed (logged — the caller still emails the lead to Ryan).
export async function captureWebLead(
  db: SupabaseClient,
  lead: { name: string; email: string | null; phone: string | null; source: WebLeadSource; followUpNote: string },
): Promise<string | null> {
  try {
    const contact = await matchOrCreateLeadContact(db, lead);
    const what = lead.source === "website-quote" ? "quote request" : "website inquiry";
    await setFollowUp(db, {
      contactId: contact.id,
      dueDate: todayCentral(),
      title: `Call ${lead.name.trim() || "new lead"} — ${what}`,
      note: lead.followUpNote,
      createdBy: "website",
    });
    return contact.id;
  } catch (e) {
    console.error("captureWebLead failed", e);
    return null;
  }
}
