-- Two-party approval for changing a contact's "Lead Generated By"
-- (contacts.sourced_by).
--
-- That field drives the Ryan/Leif commission split, so a change to it can't be
-- made unilaterally. Editing it on the contact page opens a request here; it's
-- applied to contacts.sourced_by only once every admin has approved it from
-- their own login.

CREATE TABLE IF NOT EXISTS lead_source_change_requests (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  contact_id    uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  from_value    text,
  to_value      text,
  requested_by  text NOT NULL,                     -- admin email
  requested_at  timestamptz NOT NULL DEFAULT now(),
  approved_by   text[] NOT NULL DEFAULT '{}',      -- admin emails that have approved (requester auto-included)
  status        text NOT NULL DEFAULT 'pending',   -- pending | applied | rejected | cancelled
  resolved_at   timestamptz,
  resolved_by   text
);

-- At most one open request per contact.
CREATE UNIQUE INDEX IF NOT EXISTS idx_lscr_one_pending_per_contact
  ON lead_source_change_requests (contact_id)
  WHERE status = 'pending';

-- All reads/writes go through the service-role key in
-- /api/admin/lead-source-request (which bypasses RLS and runs its own admin
-- check). Enable RLS with no policy so the anon/authenticated keys can't
-- touch this commission-sensitive table directly.
ALTER TABLE lead_source_change_requests ENABLE ROW LEVEL SECURITY;
