import HomeNav from "@/components/HomeNav";
import Link from "next/link";

export const metadata = { title: "Privacy Policy — Luck Images" };

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#0c0c0c] text-white flex flex-col">
      <HomeNav />

      <div className="pt-28 pb-24 px-6">
        <div className="max-w-2xl mx-auto">
          <p className="text-xs tracking-[4px] uppercase text-[#555] mb-3">Legal</p>
          <h1 className="text-4xl font-black tracking-tight uppercase mb-2">Privacy Policy</h1>
          <p className="text-xs text-[#444] mb-14">Last updated: August 2026</p>

          <div className="space-y-10 text-sm text-[#888] leading-relaxed">

            <section>
              <h2 className="text-xs tracking-[3px] uppercase text-[#555] mb-3">1. Information We Collect</h2>
              <p className="mb-3">We collect information you provide directly, including:</p>
              <ul className="list-none space-y-1.5 pl-4">
                <li className="before:content-['—'] before:mr-2 before:text-[#444]">Name, email address, and phone number when you book a shoot or create a portal account</li>
                <li className="before:content-['—'] before:mr-2 before:text-[#444]">Brokerage and property information related to your shoots</li>
                <li className="before:content-['—'] before:mr-2 before:text-[#444]">Payment information processed securely through our payment provider (we do not store card numbers)</li>
                <li className="before:content-['—'] before:mr-2 before:text-[#444]">Usage data when you visit our website or use the client portal (pages visited, session duration)</li>
                <li className="before:content-['—'] before:mr-2 before:text-[#444]">Link engagement data when you open tracked links we send you (click time, dwell time)</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xs tracking-[3px] uppercase text-[#555] mb-3">2. How We Use Your Information</h2>
              <ul className="list-none space-y-1.5 pl-4">
                <li className="before:content-['—'] before:mr-2 before:text-[#444]">To schedule, deliver, and invoice for photography services</li>
                <li className="before:content-['—'] before:mr-2 before:text-[#444]">To provide access to your client portal and media gallery</li>
                <li className="before:content-['—'] before:mr-2 before:text-[#444]">To send transactional emails (booking confirmations, delivery notifications, invoices)</li>
                <li className="before:content-['—'] before:mr-2 before:text-[#444]">To follow up on quotes or check in about future shoot opportunities</li>
                <li className="before:content-['—'] before:mr-2 before:text-[#444]">To improve our services based on how the portal is used</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xs tracking-[3px] uppercase text-[#555] mb-3">3. Link Tracking</h2>
              <p>
                Emails and text messages we send may include tracked links. When you click a tracked link,
                we record that a click occurred and how long you spent on the linked page. This helps us
                understand which content is useful to you. We filter automated bot clicks (such as those
                generated by iMessage link previews) and only count confirmed human interactions.
              </p>
            </section>

            <section>
              <h2 className="text-xs tracking-[3px] uppercase text-[#555] mb-3">4. Sharing Your Information</h2>
              <p className="mb-3">
                We do not sell your personal information. We share data only with:
              </p>
              <ul className="list-none space-y-1.5 pl-4">
                <li className="before:content-['—'] before:mr-2 before:text-[#444]"><span className="text-white">Supabase</span> — our database and authentication provider</li>
                <li className="before:content-['—'] before:mr-2 before:text-[#444]"><span className="text-white">Resend</span> — our email delivery provider</li>
                <li className="before:content-['—'] before:mr-2 before:text-[#444]"><span className="text-white">Vercel</span> — our hosting platform</li>
                <li className="before:content-['—'] before:mr-2 before:text-[#444]">Team members you explicitly invite to share portal access</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xs tracking-[3px] uppercase text-[#555] mb-3">5. Data Retention</h2>
              <p>
                We retain your account and shoot history for as long as you remain a client. If you request
                deletion of your account, we will remove your personal data within 30 days, except where
                retention is required for legal or accounting purposes.
              </p>
            </section>

            <section>
              <h2 className="text-xs tracking-[3px] uppercase text-[#555] mb-3">6. Security</h2>
              <p>
                Your data is stored on infrastructure with industry-standard security controls. Portal access
                is protected by authenticated login. We never store payment card details on our servers.
              </p>
            </section>

            <section>
              <h2 className="text-xs tracking-[3px] uppercase text-[#555] mb-3">7. Your Rights</h2>
              <p>
                You may request access to, correction of, or deletion of your personal data at any time by
                emailing us. We will respond within 30 days.
              </p>
            </section>

            <section>
              <h2 className="text-xs tracking-[3px] uppercase text-[#555] mb-3">8. Contact</h2>
              <p>
                Privacy questions? Email us at{" "}
                <a href="mailto:ryan@luckimages.com" className="text-white underline underline-offset-4 hover:text-[#4ade80] transition-colors">
                  ryan@luckimages.com
                </a>.
              </p>
            </section>

          </div>

          <div className="mt-14 pt-8 border-t border-white/10 flex gap-6">
            <Link href="/terms" className="text-xs tracking-[2px] uppercase text-[#555] hover:text-white transition-colors">
              Terms of Service →
            </Link>
            <Link href="/" className="text-xs tracking-[2px] uppercase text-[#555] hover:text-white transition-colors">
              ← Home
            </Link>
          </div>
        </div>
      </div>

      <footer className="border-t border-white/10 px-8 py-6 text-center mt-auto">
        <span className="text-xs tracking-[3px] uppercase text-white/20">
          © 2026 Luck Images — Austin, TX
        </span>
      </footer>
    </main>
  );
}
