import { NextResponse } from "next/server";
import { requireAdmin, createAdminClient, ADMIN_EMAILS } from "@/lib/supabase-server";

// Two-party approval for changing a contact's "Lead Generated By"
// (contacts.sourced_by) — it drives the commission split, so both admins have
// to sign off from their own login before it takes effect.

function firstName(email: string) {
  return (email.split("@")[0] || email).replace(/^./, c => c.toUpperCase());
}

async function applyRequest(db: ReturnType<typeof createAdminClient>, req: { id: string; contact_id: string; to_value: string | null }, byEmail: string) {
  await db.from("contacts").update({ sourced_by: req.to_value || null, updated_at: new Date().toISOString() }).eq("id", req.contact_id);
  await db.from("lead_source_change_requests").update({ status: "applied", resolved_at: new Date().toISOString(), resolved_by: byEmail }).eq("id", req.id);
}

// GET ?contactId=<id>  -> the open request for that contact (or null)
// GET ?pending=1        -> all open requests
export async function GET(request: Request) {
  const admin = await requireAdmin();
  if (!admin) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const db = createAdminClient();
  const { searchParams } = new URL(request.url);
  const contactId = searchParams.get("contactId");

  if (contactId) {
    const { data } = await db.from("lead_source_change_requests")
      .select("*").eq("contact_id", contactId).eq("status", "pending").maybeSingle();
    return NextResponse.json({ request: data || null });
  }

  const { data } = await db.from("lead_source_change_requests")
    .select("*, contacts(name)").eq("status", "pending").order("requested_at", { ascending: false });
  return NextResponse.json({ requests: data || [] });
}

export async function POST(request: Request) {
  const admin = await requireAdmin();
  if (!admin) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const email = admin.email!;

  const db = createAdminClient();
  const body = await request.json();
  const action: string = body.action;

  if (action === "create") {
    const { contactId, toValue } = body as { contactId: string; toValue: string | null };
    if (!contactId) return NextResponse.json({ error: "contactId required" }, { status: 400 });

    const { data: contact } = await db.from("contacts").select("id, name, sourced_by").eq("id", contactId).single();
    if (!contact) return NextResponse.json({ error: "Contact not found" }, { status: 404 });

    const current = contact.sourced_by || null;
    const next = toValue || null;
    if (current === next) return NextResponse.json({ error: "No change" }, { status: 400 });

    // Replace any existing open request for this contact.
    await db.from("lead_source_change_requests")
      .update({ status: "cancelled", resolved_at: new Date().toISOString(), resolved_by: email })
      .eq("contact_id", contactId).eq("status", "pending");

    const approvedBy = [email];
    const fullyApproved = ADMIN_EMAILS.every(a => approvedBy.includes(a));

    const { data: reqRow, error } = await db.from("lead_source_change_requests").insert({
      contact_id: contactId,
      from_value: current,
      to_value: next,
      requested_by: email,
      approved_by: approvedBy,
      status: fullyApproved ? "applied" : "pending",
      ...(fullyApproved ? { resolved_at: new Date().toISOString(), resolved_by: email } : {}),
    }).select().single();
    if (error) return NextResponse.json({ error: error.message }, { status: 500 });

    if (fullyApproved) {
      await db.from("contacts").update({ sourced_by: next, updated_at: new Date().toISOString() }).eq("id", contactId);
    } else {
      const others = ADMIN_EMAILS.filter(a => a !== email).map(firstName).join(" & ");
      await db.from("company_updates").insert({
        message: `🔀 Lead attribution change requested — ${contact.name}: ${current || "—"} → ${next || "—"}. Needs ${others}'s confirmation.`,
        created_by: "system",
        category: "admin",
        link: `/admin/contacts/${contactId}`,
      });
    }

    return NextResponse.json({ request: reqRow, applied: fullyApproved });
  }

  if (action === "approve" || action === "reject" || action === "cancel") {
    const { requestId } = body as { requestId: string };
    const { data: reqRow } = await db.from("lead_source_change_requests").select("*").eq("id", requestId).eq("status", "pending").maybeSingle();
    if (!reqRow) return NextResponse.json({ error: "Request not found or already resolved" }, { status: 404 });

    if (action === "cancel") {
      if (reqRow.requested_by !== email) return NextResponse.json({ error: "Only the requester can cancel" }, { status: 403 });
      await db.from("lead_source_change_requests").update({ status: "cancelled", resolved_at: new Date().toISOString(), resolved_by: email }).eq("id", requestId);
      return NextResponse.json({ ok: true });
    }

    if (action === "reject") {
      await db.from("lead_source_change_requests").update({ status: "rejected", resolved_at: new Date().toISOString(), resolved_by: email }).eq("id", requestId);
      const { data: c } = await db.from("contacts").select("name").eq("id", reqRow.contact_id).single();
      await db.from("company_updates").insert({
        message: `🚫 Lead attribution change rejected by ${firstName(email)} — ${c?.name || "contact"} stays ${reqRow.from_value || "—"}.`,
        created_by: "system", category: "admin", link: `/admin/contacts/${reqRow.contact_id}`,
      });
      return NextResponse.json({ ok: true });
    }

    // approve
    const approvedBy: string[] = Array.from(new Set([...(reqRow.approved_by || []), email]));
    const fullyApproved = ADMIN_EMAILS.every(a => approvedBy.includes(a));
    await db.from("lead_source_change_requests").update({ approved_by: approvedBy }).eq("id", requestId);

    if (fullyApproved) {
      await applyRequest(db, reqRow, email);
      const { data: c } = await db.from("contacts").select("name").eq("id", reqRow.contact_id).single();
      await db.from("company_updates").insert({
        message: `✅ Lead attribution changed — ${c?.name || "contact"}: ${reqRow.from_value || "—"} → ${reqRow.to_value || "—"} (confirmed by both).`,
        created_by: "system", category: "admin", link: `/admin/contacts/${reqRow.contact_id}`,
      });
    }
    return NextResponse.json({ ok: true, applied: fullyApproved });
  }

  return NextResponse.json({ error: "Unknown action" }, { status: 400 });
}
